Implemented CRUD features
cse110-fa22-group13/cse110-fa22-group13 pull request #146
Opened 2022-12-01 22:27 UTC by DouHoonKwark

1. Implemented CRUD features based on our ideas.
2. Still need to improve image src and some constraints of input
3. Also need to polish CSS and JS files

2022-12-01 23:00 UTC, Donttestturing requested changes
Need to Fix any html validator and linting issues before merging

2022-12-02 23:17 UTC, adaburton approved these changes

2022-12-02 23:22 UTC, DouHoonKwark commented
It all passed now. Thank you !

2022-12-02 23:28 UTC, Donttestturing approved these changes
Cool! We have the CRUD functionality working, as well as tests. Thank y'all for adding the Documentation too! Though that can still be improved. Thanks everybody!

2022-12-02 23:29 UTC, merged